# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a204c6db2cf4b7a3f52ae025d8ac2eb742931d57a16a036d25bd3176a9b044861858420ca79115d101cb5552dac83b2883b75a2eca2b4a77b2a1fe456379b7f

test:
  secret_key_base: d50b91075f4342fbe22ae1484632781a82a5d1fd3816eddd42278256fe6c3d5675b56d1ca675b9a1d782bea7dd02f7519d8b82ab12569848b2ae2db40ffc03ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
